aliases.matpairs:
    granite: stone/1
    polgranite: stone/2
    diorite: stone/3
    poldiorite: stone/4
    andesite: stone/5
    polandesite: stone/6
    brick: smooth_brick/0
    carvedbrick: smooth_brick/3
    stairs: smooth_stairs/0
    clay: stained_clay/0
    
matlist:
    default:
        - mats.test2
    desert:
        - mats.sand
    nether:
        - mats.nether

mats:
    default:
        primary:
            - brick
        secondary:
            - stone
            - polandesite
            - poldiorite
        supsecondary:
            - gravel
        ornament:
            - carvedbrick
        stair:
            - stairs
            - birch_wood_stairs
            - jungle_wood_stairs
            - spruce_wood_stairs
        fence:
            - fence
            - cobble_wall
            - iron_fence
        roofsteps:
            - smooth_stairs
            - wood_stairs
            - birch_wood_stairs
            - jungle_wood_stairs
            - spruce_wood_stairs
            - obsidian
        ground:
            - grass
            - gravel
            - sand
        pole:
            - wood
            - cobble_wall
        window:
            - thin_glass
    sand:
        primary:
            - sandstone/1
        secondary:
            - sandstone/0
        supsecondary:
            - sand
        ornament:
            - sandstone/2
        stair:
            - sandstone_stairs
            - birch_wood_stairs
        fence:
            - fence
            - iron_fence
        roofsteps:
            - sandstone_stairs
            - birch_wood_stairs
        ground:
            - sand
        pole:
            - wood
        window:
            - thin_glass
    nether:
        primary:
            - nether_brick
        secondary:
            - nether_brick
        supsecondary:
            - gravel
        ornament:
            - red_sandstone
        stair:
            - nether_brick_stairs
            - red_sandstone_stairs
        fence:
            - nether_fence
            - iron_fence
        roofsteps:
            - nether_brick_stairs
            - red_sandstone_stairs
        ground:
            - soul_sand
            - netherrack
        pole:
            - nether_brick
        window:
            - iron_fence
    cobble:
        primary:
            - cobblestone
        secondary:
            - cobblestone
        supsecondary:
            - gravel
        ornament:
            - cobblestone/3
        stair:
            - cobblestone_stairs
        fence:
            - iron_fence
            - cobble_wall
            - fence
        roofsteps:
            - wood_stairs
            - cobblestone_stairs
        ground:
            - gravel
        pole:
            - cobble_wall
            - fence
        window:
            - thin_glass
    test:
        primary:
            - clay/0
            - clay/1
            - clay/2
            - clay/3
            - clay/4
            - clay/5
            - clay/6
            - clay/7
            - clay/8
            - clay/9
            - clay/10
            - clay/11
            - clay/12
            - clay/13
            - clay/14
            - clay/15

    test2:
        base: mats.test
        secondary:
            - stone
        fence:
            - cobble_wall
                
