# These are aliases for material/databyte pairs which can be used
# in material sets. A material/databyte pair is normally
# ID/DATA but if the data is omitted, 0 is assumed for the databyte.
#
# In using an alias, it's possible to override the provided databyte.
# For example, given the list below, "clay" normally means stained_clay/0,
# but "clay/4" will map to stained_clay/4.

aliases.matpairs:
    granite: stone/1
    polgranite: stone/2
    diorite: stone/3
    poldiorite: stone/4
    andesite: stone/5
    polandesite: stone/6
    brick: smooth_brick/0
    carvedbrick: smooth_brick/3
    stairs: smooth_stairs/0
    clay: stained_clay/0
    oakwood: wood/0
    sprucewood: wood/1
    birchwood: wood/2
    junglewood: wood/3
    acaciawood: wood/4
    darkoakwood: wood/5
    oaklog: log/0
    sprucelog: log/1
    birchlog: log/2
    junglelog: log/3
    acacialog: log_2/0
    darkoaklog: log_2/1

#
# These lists define the material sets to be used for each biome.
# Each new building in that biome will then use a random member
# of the list as its material set. Biome names here must be full
# names. If a biome is not named here, first a match will be looked
# for in the "matmatch" lists. If one is not found, the default will
# be used (a default must be provided).
#    
matlist:
    default:
        - mats.default
    desert:
        - mats.sand
    nether:
        - mats.nether

# These lists define material sets for those biomes not in the matlist
# above. The keys are regular expressions, but "*" is replaced with ".*"
# because of YAML not permitting "." inside a key.
#
# This list is only used if the biome is not present, by its full name,
# in the matlist. If it is also not found here, the default entry in the
# matlist is used.

matmatch:
    "*taiga*":
        - mats.taiga
    "frozen*":
        - mats.taiga
    "ice*":
        - mats.taiga    

# These are the material sets which are referred to by the lists above.
# Each entry within a set is used for a particular type of block inside
# the castle:
#
# primary -     used for most of the building
# secondary -   used for a bit of variety in Turtle building (columns,
#               roof crenellation), but also to underfill floating
#               buildings and for garden patterning.
# supsecondary- a loose building material which is subject to gravity,
#               like sand or gravel. Used in crenellation.
# ornament -    used for decorative blocks
# stair -       for stair exits
# fence -       for roof and interior fencing
# roofsteps -   for constructing pitched roofs
# ground -      for gardens and paths (and roof gardens).
# pole -        for some columns and parts of columns
# window -      for windows. If this is thin_glass, the window may
#               become a patterned stained-glass window.
#
# Inheritance
# It is possible for one material set to inherit any lists it doesn't
# explicitly specify from another, either using YAML's merge facility
# or by setting a base: key to the name of another material set,
# e.g. "base: mats.cobble".
# All sets inherit the set called "default".


mats:
    default:
        primary:
            - brick
        secondary:
            - stone
            - polandesite
            - poldiorite
        supsecondary:
            - gravel
        ornament:
            - carvedbrick
        door:
            - wood_door
            - wood_door
            - wood_door
            - spruce_door
            - dark_oak_door
            - acacia_door
            - birch_door
            - iron_door
            - jungle_door
        stair:
            - stairs
            - birch_wood_stairs
            - jungle_wood_stairs
            - spruce_wood_stairs
        fence:
            - fence
            - cobble_wall
            - iron_fence
        roofsteps:
            - smooth_stairs
            - wood_stairs
            - birch_wood_stairs
            - jungle_wood_stairs
            - spruce_wood_stairs
            - obsidian
        ground:
            - grass
            - gravel
            - sand
        pole:
            - wood
            - cobble_wall
        window:
            - thin_glass
        floor:
            - stone
            - polandesite
            - birchwood
    sand:
        primary:
            - sandstone/1
        secondary:
            - sandstone/0
        supsecondary:
            - sand
        ornament:
            - sandstone/2
        stair:
            - sandstone_stairs
            - birch_wood_stairs
        fence:
            - fence
            - iron_fence
        roofsteps:
            - sandstone_stairs
            - birch_wood_stairs
        ground:
            - sand
        pole:
            - wood
        window:
            - thin_glass
    nether:
        primary:
            - nether_brick
        secondary:
            - nether_brick
        supsecondary:
            - gravel
        ornament:
            - red_sandstone
        stair:
            - nether_brick_stairs
            - red_sandstone_stairs
        fence:
            - nether_fence
            - iron_fence
        roofsteps:
            - nether_brick_stairs
            - red_sandstone_stairs
        ground:
            - soul_sand
            - netherrack
        pole:
            - nether_brick
        window:
            - iron_fence
    cobble:
        primary:
            - cobblestone
        secondary:
            - cobblestone
        supsecondary:
            - gravel
        ornament:
            - cobblestone/3
        stair:
            - cobblestone_stairs
        fence:
            - iron_fence
            - cobble_wall
            - fence
        roofsteps:
            - wood_stairs
            - cobblestone_stairs
        ground:
            - gravel
        pole:
            - cobble_wall
            - fence
        window:
            - thin_glass
    taiga:
        stair:
            - spruce_wood_stairs
            - stairs
        fence:
            - cobble_wall
            - iron_fence
        ground:
            - snow_block
            - grass
