name: Gorm
main: org.pale.gorm.GormPlugin
version: 1.1
commands:
  build:
    description: Build the next room
    usage: /build
    permission: Gorm.build
    permission-message: You don't have permission
  startgorm:
    description: Start Gorming!
    usage: /startgorm
    permission: Gorm.build
    permission-message: You don't have permission
  stopgorm:
    description: Stop Gorming!
    usage: /stopgorm
    permission: Gorm.build
    permission-message: You don't have permission
  gormconf:
    description: Reload config
    usage: /gormconf
    permission: Gorm.build
    permission-message: You don't have permission
  razegorm:
    description: Flatten and demolish
    usage: /razegorm
    permission: Gorm.build
    permission-message: You don't have permission
  deni:
    description: List types of castle denizens
    usage: /deni
    permission: Gorm.build
    permission-message: You don't have permission
  shb:
    description: Fill blocked regions of current room
    usage: /shb
    permission: Gorm.build
    permission-message: You don't have permission
  mke:
    description: Make exit from current room to lookedat room
    usage: /mke
    permission: Gorm.build
    permission-message: You don't have permission
  gt:
    description: Run the gorm turtle
    usage: /test [string]
    permission: Gorm.build
    permission-message: You don't have permission
  flatten:
    description: Crush the land!
    usage: /flatten
    permission: Gorm.build
    permission-message: You don't have permission
  roominfo:
    description: Show room/building details
    usage: /roominfo
    permission: Gorm.build
    permission-message: You don't have permission
  resetgorm:
    description: Delete the castle data structures
    usage: /resetgorm
    permission: Gorm.build
    permission-message: You don't have permission
  snark:
    description: general debugging command
    usage: /snark
    permission: Gorm.build
    permission-message: You don't have permission
  splode:
    description: make a huge bang, for demolishing tests
    usage: /splode
    permission: Gorm.build
    permission-message: You don't have permission
